export default {
    ADD_USER: 'ADD_USER',
    RECEIVE_MSG: 'RECEIVE_MSG',
    // SEND_MSG: 'SEND_MSG'
    ERROR_OCCURED: 'ERROR_OCCURED',
    RESET_STATUS: 'RESET_STATUS',
    SET_INFO: 'SET_INFO'
}
